# Site settings
title: 김만명
email: manmyung@gmail.com
# description: > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://manmyung.github.io" # the base hostname & protocol for your site
twitter_username: manmyung
github_username: manmyung

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]

highlighter: pygments

gems:
  - jekyll-redirect-from
